-- Here are some of the exercises for which you can write SQL queries to self evaluate using all the concepts we have learnt to write SQL Queries.
-- * All the exercises are based on retail tables.
-- * We have already setup the tables and also populated the data.
-- * We will use all the 6 tables in retail database as part of these exercises.

Here are the commands to validate the tables
SELECT count(*) FROM departments;
SELECT count(*) FROM categories;
SELECT count(*) FROM products;
SELECT count(*) FROM orders;
SELECT * FROM order_items;
SELECT count(*) FROM customers;

-- ### Exercise 1 - Customer order count

-- Get order count per customer for the month of 2014 January.

select c.customer_id,
    c.customer_fname,
    c.customer_lname,
    count(o.order_id) as customer_order_count
from customers as c
    left join orders as o
        on c.customer_id = o.order_customer_id
where to_char(o.order_date, 'yyyy-MM') = '2014-01'
group by c.customer_id, c.customer_fname, c.customer_lname
order by customer_order_count desc, c.customer_id asc;


-- * Tables - `orders` and `customers`
-- * Data should be sorted in descending order by count and ascending order by customer id.
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname` and `customer_order_count`.

-- ### Exercise 2 - Dormant Customers

-- Get the customer details who have not placed any order for the month of 2014 January.
select count(*) FROM 
customers as c
where c.customer_id not in
(   select c.customer_id
    from customers as c
    join orders as o
        on c.customer_id = o.order_customer_id
        and to_char(o.order_date, 'yyyy-MM') = '2014-01'
)

-- * Tables - `orders` and `customers`
-- * Output Columns - **All columns from customers as is**
-- * Data should be sorted in ascending order by `customer_id`
-- * Output should contain all the fields from `customers`
-- * Make sure to run below provided validation queries and validate the output.

SELECT count(DISTINCT order_customer_id)
FROM orders
WHERE to_char(order_date, 'yyyy-MM') = '2014-01';

SELECT count(*)
FROM customers;

-- Get the difference
-- Get the count using solution query, both the difference and this count should match

-- * Hint: You can use `NOT IN` or `NOT EXISTS` or `OUTER JOIN` to solve this problem.

-- ### Exercise 3 - Revenue Per Customer

-- Get the revenue generated by each customer for the month of 2014 January

select c.customer_id, c.customer_fname, c.customer_lname, COALESCE(SUM(oi.order_item_subtotal), 0) as customer_revenue
    from customers as c
    left join orders as o
    left join order_items as oi
        on c.customer_id = o.order_customer_id
        and o.order_id = oi.order_item_order_id
        and to_char(o.order_date, 'yyyy-MM') = '2014-01'
group by c.customer_id, c.customer_fname, c.customer_lname
order by customer_revenue desc, c.customer_id asc;

-- * Tables - `orders`, `order_items` and `customers`
-- * Data should be sorted in descending order by revenue and then ascending order by `customer_id`
-- * Output should contain `customer_id`, `customer_fname`, `customer_lname`, `customer_revenue`.
-- * If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
-- * Consider only `COMPLETE` and `CLOSED` orders

-- ### Exercise 4 - Revenue Per Category

-- Get the revenue generated for each category for the month of 2014 January

SELECT c.category_id, c.category_department_id, c.category_name, COALESCE(SUM(oi.order_item_subtotal), 0) AS category_revenue
FROM categories AS c
    LEFT JOIN products AS p
        ON c.category_id = p.product_category_id
    LEFT JOIN order_items AS oi
        ON p.product_id = oi.order_item_product_id
    LEFT JOIN orders AS o
        ON oi.order_item_order_id = o.order_id
        AND to_char(o.order_date, 'yyyy-MM') = '2014-01'
WHERE o.order_status IN ('COMPLETE', 'CLOSED')
GROUP BY c.category_id, c.category_department_id, c.category_name
ORDER BY c.category_id ASC;

-- * Tables - `orders`, `order_items`, `products` and `categories`
-- * Data should be sorted in ascending order by `category_id`.
-- * Output should contain all the fields from `categories` along with the revenue as `category_revenue`.
-- * Consider only `COMPLETE` and `CLOSED` orders

-- ### Exercise 5 - Product Count Per Department

select d.department_id, d.department_name, COALESCE(COUNT(p.product_id), 0) AS product_count
FROM departments AS d
    LEFT JOIN categories AS c
        ON d.department_id = c.category_department_id
    LEFT JOIN products AS p         
        ON c.category_id = p.product_category_id
GROUP BY d.department_id, d.department_name
ORDER BY d.department_id ASC;   

-- Get the count of products for each department.
-- * Tables - `departments`, `categories`, `products`
-- * Data should be sorted in ascending order by `department_id`
-- * Output should contain all the fields from `departments` and the product count as `product_count`